name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migration
      run: ${{ github.workspace }}/manage.py migrate
    - name: Run Server
      run: python ${{ github.workspace }}/manage.py runserver >/dev/null 2>&1 </dev/null & disown  
    - name: BrowserStack Actions
      # You may pin to the exact commit or the version.
      # uses: browserstack/github-actions@00ce173eae311a7838f80682a5fad5144c4219ad
      uses: browserstack/github-actions@v1.0.1
      with:
        # BrowserStack Username
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
        # BrowserStack Access Key
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: 'Start BrowserStackLocal Tunnel'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
          local-testing: start
          local-logging-level: all-logs
          local-identifier: random
    - name: Install
      working-directory: ./demosite
      run: yarn
    - name: Percy Test
      working-directory: ./demosite
      run: npx percy exec -- cypress run
      env:
          BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
          BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_ENABLE: 1
    - name: 'Stop BrowserStackLocal'
      uses: 'browserstack/github-actions/setup-local@master'
      with:
          local-testing: 'stop'

    
